Add verify address button to Receive modal
spacemeshos/smapp-lite pull request #83
Opened 2024-09-10 13:06 UTC by brusherru

It is requested by Ledger company to add a "verify" button on "Receive" modal, that asks User to verify the address on his Ledger device. So now it is implemented.

It may require design improvement or rephrasing.

<img width="588" alt="image" src="https://github.com/user-attachments/assets/c318bf07-8f98-4501-9d06-cc16fd8b21c7">
<img width="588" alt="image" src="https://github.com/user-attachments/assets/d740443e-a6d3-421e-910b-087821570f4c">
<img width="588" alt="image" src="https://github.com/user-attachments/assets/83e7e881-9595-4a4b-9d36-1fee1a3b4b6e">

And there is also possible another case with red text, saying: "The address is incorrect, probably you are using another Ledger device." :)

2024-09-10 14:26 UTC, monikasmolarek requested changes
Once the address check is rejected on the ledger, it gets automatically the modal claiming (incorrectly) the ledger is disconnected. 

+ the error messages were messy🤔

https://github.com/user-attachments/assets/fab38f2a-478e-4ff5-ad11-de5084af355a

2024-09-10 14:26 UTC, monikasmolarek commented on src/components/Receive.tsx
> +                match the address above.
```suggestion
                Please review the address on the Ledger device and approve if it 
                matches the address above.
```

2024-09-11 22:36 UTC, brusherru commented
@monikasmolarek thanks!
Fixed. There are two new messages for the cases:
1. When the address is rejected on the device, it does not require to reconnect anymore, but displays:
   <img width="589" alt="image" src="https://github.com/user-attachments/assets/76063e6c-c585-42c2-926f-7898be94609a">
    
2. When the device is locked or not connected there will be another message (in case User closes the "connect device" popup). Example:
    <img width="589" alt="image" src="https://github.com/user-attachments/assets/e2eebaec-e472-4814-ab9c-3d579778a2d1">
    <img width="589" alt="image" src="https://github.com/user-attachments/assets/a237355f-5e09-418c-bfb1-e04c9edbc42d">

2024-09-11 23:06 UTC, monikasmolarek reviewed
@brusherru This is indeed fixed, thanks ! 
but please double-check the case when you start the address verification, you don't do anything on the ledger, so the request there is waiting for your approve/reject, but in the Wallet you click OK or close the modal etc. 
When the tx/action is pending on the device, the Wallet gets really confused about the device connection. 

https://github.com/user-attachments/assets/e45e9763-9109-40df-93e5-fbdcc5a10720

My steps in this rec: 
1. opened receive, clicked verify -> checked the device but didn’t approve or reject, left pending
2. clicked OK on the modal
3. opened receive, clicked verify again-> the reconnect modal appeared
4. took device, approved the request -> it got approved "in the background" below the reconnect modal
5. the wallet got confused about the connection

2024-09-13 23:21 UTC, brusherru commented
> When the tx/action is pending on the device, the Wallet gets really confused about the device connection.

The problem here that we cannot cancel the operation on the ledger device if you close the window.
And at the same time, Ledger works in a synchronous way, which means if you run another operation while the previous one was not finished — it causes transport error, which also causes disconnecting from the device.

The only thing I can do here is to disable closing the popup once "Verify" button was clicked.
So I tweaked it, and hopefully it will work well :D

<img width="588" alt="image" src="https://github.com/user-attachments/assets/64397276-0c55-4abf-b4c4-659eb82954de">


However, if you reload the page and click "Verify" once again — we don't have any chance to handle it properly in the app.

2024-09-17 02:44 UTC, brusherru commented
Ok, I'm pretty sure it is fine, so I'm merging it.
If we find out any problems — I'll fix it :)

2024-09-17 02:44 UTC, merged